add push button
openstax/poet pull request #19
Opened 2021-02-23 17:24 UTC by ckline-tryptic

2021-03-17 21:11 UTC, tomjw64 requested changes

2021-03-17 21:11 UTC, tomjw64 commented on client/src/test/suite/extension.test.ts
> +      stubRepo.commit = sinon.stub().throws(GitErrorCodes.Conflict)
the `commit` function can never throw an error formed this way. Also, `pushContent` should **not** throw in the case of a conflict, so the assertion in this test doesn't seem correct

2021-03-17 21:11 UTC, tomjw64 commented on client/src/test/suite/extension.test.ts
> +      assert((e.stdout as string).includes('nothing to commit'))
`pushContent` also should not throw in this case

2021-03-18 15:11 UTC, ckline-tryptic commented
Wrote tests, but code Codecov was complaining, and code that it looks like my tests would cover are reported as not covered. Making some changes to resolve this.

2021-03-18 15:25 UTC, ckline-tryptic commented on client/src/push-content.ts
> +  const repo = getRepo()
Mayhaps, it's mainly the repo itself that needs mocking.

2021-03-18 20:43 UTC, ckline-tryptic commented on LICENSE2
> +MIT License
Moving the interface and license files into their own directory.

2021-03-18 22:20 UTC, closed without merging