Portable model
openstax/poet pull request #96
Opened 2021-08-09 15:21 UTC by philschatz

I tried to add a few book validations from the errors we encountered last week with the vendor using the editor (Pages with duplicate UUID, chapters with the same name, modules in the book twice) but had trouble wrapping my head around all the caching & async communication going on.

This changes the language server in the following ways:

- disconnects the book model from VSCode, Promises, the filesystem reads/writes, and Caches.
- there is one place to update the model and the user gets immediate validation errors (or a lost of nodes that need to be loaded first)
- There is one instance of every file in the model
- If a file does not exist (like for broken links) it is still instantiated but `.isEmpty()` is true

All the filesystem/vscode parts were moved into `model-adapter.ts`.

Also, there are some changes to the Job ~~Queue~~ Stack:
- The server enqueues all the book loading onto a "slow" ~~queue~~ _stack_
- Whenever a file is opened a job is added to the "fast" ~~queue~~ _stack_
- Whenever validation requires loading other files (like the link target page, or a target image) those get added to the stack and then the validation re-reports (another job on the stack)

Now, adding a validation message requires adding an entry into the model that looks like this:

```js
public getValidationChecks(): ValidationCheck[] {
    const imageLinks = this.imageLinks()
    return [
        {
            message: 'Missing image',
            nodesToLoad: imageLinks.map(l => l.image),
            fn: () => imageLinks.filter(img => !img.image.exists())
        }
    ]
}
```

Once all the dependent nodes are loaded, the Job Stack will re-run the validation check and report any errors that occur.

2021-08-16 11:01 UTC, ckline-tryptic commented on server/src/model-manager.spec.ts
> +    expect(manager.orhpanedPages().size).toBe(0)
small spelling error

2021-08-16 13:23 UTC, philschatz commented on server/src/model-manager.spec.ts
> +    expect(manager.orhpanedPages().size).toBe(0)
:blush: The downside of autocompletion. Fixed!

2021-08-19 21:58 UTC, therealmarv requested changes

2021-08-19 21:58 UTC, therealmarv commented on server/src/README.md
> +npx ts-node@10.1.0 ./_cli.ts /path/to/book/repo /path/to/another/book/repo
minor: model directory missing

```npx ts-node@10.1.0 ./model/_cli.ts /path/to/book/repo /path/to/another/book/repo```

2021-08-19 22:07 UTC, philschatz commented on server/src/README.md
> +npx ts-node@10.1.0 ./_cli.ts /path/to/book/repo /path/to/another/book/repo
Oops :blush: . Fixed!

2021-08-19 22:11 UTC, therealmarv approved these changes
For my point of view this are big changes (I mean that positive). I still have not wrapped my head around it fully but I like it what I see and I could test.

2021-08-23 20:06 UTC, ckline-tryptic approved these changes

2021-08-23 20:45 UTC, philschatz commented on server/src/model/_cli.ts
> +;(async function () {
The self-invoked function is the only way to _sort of_ use `await` in the global scope. The semicolon is often optional but in this case JS would be confused and think that we broke the following expression onto multiple lines :shrug: `const pathHelper = {...}(...)`

![image](https://user-images.githubusercontent.com/253202/130516637-ec1fa38b-27bf-4a68-bd0e-ce29f39ce6a0.png)

2021-08-23 20:45 UTC, philschatz commented on server/src/README.md
> +Nodes are instantiated by a Factoryies on the Bundle.
Thanks, fixed!

2021-08-25 14:57 UTC, merged